name = "mentraos-llm"
main = "dist/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "mira-llm-prod"

[env.development]
name = "mira-llm-dev"

# Add your environment variables here
[vars]
NODE_ENV = "production"
LLM_PROVIDER = "perplexity"
LLM_MODEL = "sonar"

# For LangChain and other Node.js dependencies
[build]
command = "npm run build:worker"

# KV namespace for session persistence
# Note: For production deployment, you'll need to set these IDs via:
# wrangler secret put MENTRAOS_LLM_KV_ID
# Or use the dashboard to configure KV bindings
[[kv_namespaces]]
binding = "MENTRAOS_LLM"
id = "f32ef2dce1764334adef836a586b07ae"  # This will need to be configured for production
preview_id = "5b6184536ae44c0499edec3be25794e8"

# Durable Objects for session management with SQLite backend (FREE storage)
[durable_objects]
bindings = [
  { name = "MENTRAOS_LLM_SESSIONS", class_name = "MentraOSSessionManager" }
]

# Migration to enable SQLite storage backend (FREE)
[[migrations]]
tag = "v1"
new_sqlite_classes = ["MentraOSSessionManager"]

[observability.logs]
enabled = true
