name = "mentraos-llm"
main = "dist/worker-simple.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "mira-llm-prod"

[env.development]
name = "mira-llm-dev"

# Add your environment variables here
[vars]
NODE_ENV = "production"
LLM_PROVIDER = "perplexity"
LLM_MODEL = "sonar"

# For LangChain and other Node.js dependencies
[build]
command = "npm run build:worker"

# KV namespace for session persistence - run: npx wrangler kv namespace create mentraos-llm
# Then replace <GENERATED_NAMESPACE_ID> with the actual ID from the command output
kv_namespaces = [
  { binding = "MENTRAOS_LLM", id = "<GENERATED_NAMESPACE_ID>" }
]

# Durable Objects for session management with SQLite backend (FREE storage)
[durable_objects]
bindings = [
  { name = "MENTRAOS_LLM_SESSIONS", class_name = "MentraOSSessionManager" }
]

# Migration to enable SQLite storage backend (FREE)
[[migrations]]
tag = "v1"
new_sqlite_classes = ["MentraOSSessionManager"]

[observability.logs]
enabled = true
